### ISSUE TITLE
Minimum phase filter?

### ISSUE THREAD

**Issue by Cat-Ion** [erdewit/HiFiScan#9]
Hey, thanks for writing this program, it's been really useful! :)

Have you considered adding an option to use a minimum phase filter instead of zero phase? That would allow to have less perceived latency for longer outputs, and would also reduce the pre-ringing for all filters. AutoEq already implements this [here](https://github.com/jaakkopasanen/AutoEq/blob/master/frequency_response.py#L364).

**Comment by erdewit** [comment]
Yes, I had seen the AutoEq code and was wondering why anyone would want to use minimum phase. The filter is halve the size of the linear phase filter, but the peak is at the beginning instead of in the middle, which gives both filters the same latency. While there is no pre-ringing, there is twice the post-ringing, plus phase distortion (this can get severe with a steep-sloped equalization). I think any potential ringing is better addressed with tapering and smoothing.

These are just my thoughts at this moment, please feel free to share yours.

**Comment by erdewit** [comment]
To correct myself, I forgot that when convolving the filter is in effect flipped. This would give the minimum phase filter a close to zero latency. That is a good enough reason to add it and I will do so.

**Comment by erdewit** [comment]
This is added in v1.3.0. There is a new **Causality** parameter that is set to 100% for a minimal-phase filter and 0% for a linear-phase filter. When looking deeper into the math I found a way to get smooth transitions between these two extremes. This looks like to be a novel technique and it's very useful for controlling the balance of pre- and post echos, as well as the latency.

A causality of 35 to 50% seems to be a sweet spot and sounds very good.
